# Generated by Django 3.0.3 on 2020-02-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_create',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del Post')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('descripcion', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('imagen', models.URLField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_Create', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
    ]
